package `in`.jphe.storyvox.auth.anthropic

import `in`.jphe.storyvox.llm.LlmCredentialsStore
import `in`.jphe.storyvox.llm.auth.AnthropicTeamsAuthApi
import `in`.jphe.storyvox.llm.auth.AnthropicTeamsAuthRepository
import `in`.jphe.storyvox.llm.auth.TokenResult
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import okhttp3.OkHttpClient
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * #692 — Anthropic's `console.anthropic.com/oauth/code/callback` page
 * renders the authorization code as `<code>#<state>`. The token endpoint
 * rejects the full pasted string as `invalid_grant` ("Invalid 'code' in
 * request"). The VM must split on `#` and only send the prefix as `code`.
 *
 * Robolectric runner because [PkcePair] reaches for `android.util.Base64`
 * during `openBrowser()` — same as the existing [PkcePairTest].
 */
@OptIn(ExperimentalCoroutinesApi::class)
@RunWith(RobolectricTestRunner::class)
@Config(application = android.app.Application::class)
class AnthropicTeamsSignInViewModelTest {

    private val dispatcher = StandardTestDispatcher()

    @Before
    fun setUp() {
        Dispatchers.setMain(dispatcher)
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    @Test
    fun `submitCode splits pasted code#state and sends only code to token endpoint`() =
        runTest(dispatcher) {
            val api = RecordingApi(TokenResult.Success("bearer", "refresh", 3600, "scope", "Bearer"))
            val vm = AnthropicTeamsSignInViewModel(api, repo()).also { it.clientIdOverride = "c" }
            vm.openBrowser()

            vm.submitCode("real-code-abc#state-nonce-xyz")
            advanceUntilIdle()

            assertNotNull("exchangeCode was not called", api.lastExchange)
            assertEquals("real-code-abc", api.lastExchange!!.code)
            assertEquals("state-nonce-xyz", api.lastExchange!!.state)
            assertTrue(vm.state.value is SignInState.Captured)
        }

    @Test
    fun `submitCode tolerates trailing whitespace around the pasted blob`() =
        runTest(dispatcher) {
            val api = RecordingApi(TokenResult.Success("bearer", null, 3600, "scope", "Bearer"))
            val vm = AnthropicTeamsSignInViewModel(api, repo()).also { it.clientIdOverride = "c" }
            vm.openBrowser()

            vm.submitCode("   real-code#state-nonce\n")
            advanceUntilIdle()

            assertEquals("real-code", api.lastExchange!!.code)
            assertEquals("state-nonce", api.lastExchange!!.state)
        }

    @Test
    fun `submitCode without # falls back to pending state and sends full code`() =
        runTest(dispatcher) {
            val api = RecordingApi(TokenResult.Success("bearer", null, 3600, "scope", "Bearer"))
            val vm = AnthropicTeamsSignInViewModel(api, repo()).also { it.clientIdOverride = "c" }
            vm.openBrowser()

            vm.submitCode("bare-code-without-state")
            advanceUntilIdle()

            assertEquals("bare-code-without-state", api.lastExchange!!.code)
            // Pending state nonce (generated by openBrowser) should be non-blank.
            assertTrue(
                "expected pendingState fallback, got '${api.lastExchange!!.state}'",
                api.lastExchange!!.state.isNotBlank(),
            )
        }

    @Test
    fun `submitCode with only #state is rejected before hitting the endpoint`() =
        runTest(dispatcher) {
            val api = RecordingApi(TokenResult.Success("bearer", null, 3600, "scope", "Bearer"))
            val vm = AnthropicTeamsSignInViewModel(api, repo()).also { it.clientIdOverride = "c" }
            vm.openBrowser()

            vm.submitCode("#orphan-state")
            advanceUntilIdle()

            assertNull("exchangeCode should not have been called", api.lastExchange)
            assertTrue(vm.state.value is SignInState.Failure)
        }

    @Test
    fun `invalid_grant surfaces as retryable Failure with Anthropic message`() =
        runTest(dispatcher) {
            val api = RecordingApi(TokenResult.InvalidGrant("Invalid 'code' in request."))
            val vm = AnthropicTeamsSignInViewModel(api, repo()).also { it.clientIdOverride = "c" }
            vm.openBrowser()

            vm.submitCode("code#state")
            advanceUntilIdle()

            val failure = vm.state.value as SignInState.Failure
            assertTrue(failure.retryable)
            assertTrue(
                "expected Anthropic message in failure copy, got '${failure.message}'",
                failure.message.contains("Invalid 'code' in request."),
            )
        }

    private fun repo(): AnthropicTeamsAuthRepository =
        AnthropicTeamsAuthRepository(FakeCredentialsStore())

    private class RecordingApi(private val result: TokenResult) :
        AnthropicTeamsAuthApi(OkHttpClient()) {

        data class ExchangeCall(val code: String, val verifier: String, val state: String)

        var lastExchange: ExchangeCall? = null
            private set

        override fun authorizeUrl(
            clientId: String,
            scopes: String,
            challenge: String,
            state: String,
        ): String = "https://claude.ai/oauth/authorize?state=$state"

        override suspend fun exchangeCode(
            clientId: String,
            code: String,
            verifier: String,
            state: String,
        ): TokenResult {
            lastExchange = ExchangeCall(code, verifier, state)
            return result
        }
    }

    private class FakeCredentialsStore : LlmCredentialsStore(
        org.robolectric.RuntimeEnvironment.getApplication()
            .getSharedPreferences("test-prefs", android.content.Context.MODE_PRIVATE),
    ) {
        private var bearer: String? = null
        private var refresh: String? = null
        private var expiresAt: Long = 0
        private var scopes: String? = null

        override val hasTeamsToken: Boolean get() = bearer != null
        override fun teamsScopes(): String? = scopes

        override fun setTeamsSession(
            bearer: String,
            refreshToken: String?,
            expiresAtEpochMillis: Long,
            scopes: String,
        ) {
            this.bearer = bearer
            this.refresh = refreshToken
            this.expiresAt = expiresAtEpochMillis
            this.scopes = scopes
        }

        override fun clearTeamsSession() {
            bearer = null
            refresh = null
            expiresAt = 0
            scopes = null
        }
    }
}
