import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    // Issue #417 — :app needs kotlinx-serialization to JSON-encode the
    // user's starred radio stations in RadioConfigImpl.
    alias(libs.plugins.kotlin.serialization)
    // Issue #409 — consumer side of the Baseline Profile plugin pair.
    // Pulls the generated `baseline-prof.txt` from :baselineprofile into
    // `app/src/main/baseline-prof.txt` so it's packaged into the APK.
    // The producer (`:baselineprofile`) emits the profile via
    // `BaselineProfileRule`; the plugin wires
    // `:app:generateBaselineProfile` → that producer task and copies
    // the result into :app's main sourceSet. ProfileInstaller (added
    // below as a runtime dep) compiles the profile at install time.
    alias(libs.plugins.androidx.baselineprofile)
    // Triple-T gradle-play-publisher — `./gradlew publishReleaseBundle`
    // uploads the signed AAB to Play Console's Internal Test track without
    // touching the browser. Plugin always applies; the `play { }` block
    // below is conditionally configured so this is a no-op until JP drops
    // a service-account JSON path into local.properties. See
    // docs/play-store/RUNBOOK.md for the one-time service-account setup.
    alias(libs.plugins.play.publisher)
}

/**
 * Realm-sigil git provenance — captured at configure time so BuildConfig
 * can carry hash/branch/dirty/built fields. Uses [providers.exec] which is
 * configuration-cache-compatible, unlike a raw [ProcessBuilder]. Failures
 * fall back to "dev" so non-git checkouts (source tarballs) still build.
 */
fun gitOutput(vararg args: String): String = runCatching {
    val output = providers.exec {
        commandLine("git", *args)
        workingDir = rootDir
    }
    output.standardOutput.asText.get().trim()
}.getOrDefault("dev")

val gitHash: String = gitOutput("rev-parse", "--short=8", "HEAD").ifBlank { "dev" }
val gitBranch: String = gitOutput("rev-parse", "--abbrev-ref", "HEAD").ifBlank { "unknown" }
val gitDirty: Boolean = gitOutput("status", "--porcelain").isNotEmpty()
val buildTime: String = gitOutput("log", "-1", "--format=%cI", "HEAD").ifBlank { "dev" }

/**
 * Play Store release keystore — opt-in via local.properties (gitignored).
 *
 * The repo still ships a checked-in debug keystore (see signingConfigs.debug
 * below) which signs every variant by default — that's what keeps sideload
 * upgrade continuity working from v0.4.15 onward, and what every CI runner
 * and contributor's machine has used since.
 *
 * The Play Store will NOT accept the checked-in debug keystore (Google's
 * upload check rejects keys generated by `keytool -genkey -keystore
 * debug.keystore -storepass android`). Once JP has generated a real
 * release keystore (see docs/release-keystore.md), the four properties
 * below — read from a gitignored `local.properties` — wire it in as the
 * `release` signing config.
 *
 *   storyvox.releaseStoreFile=/home/jp/.storyvox-keystore/storyvox-release.keystore
 *   storyvox.releaseStorePassword=...
 *   storyvox.releaseKeyAlias=storyvox
 *   storyvox.releaseKeyPassword=...
 *
 * When all four are present AND the file exists, the Play AAB path
 * (`bundleRelease` / `publishReleaseBundle`) signs with this keystore;
 * see `isBundleOrPublishBuild` and the comment in `buildTypes.release`
 * for the split heuristic added in #952. The sideload APK path
 * (`assembleRelease`) deliberately ignores this keystore and signs
 * with the checked-in debug keystore, preserving upgrade continuity
 * from every install since v0.4.15.
 *
 * When ANY of the four are missing or the file is absent, both paths
 * fall back to the checked-in debug keystore — preserving the today
 * behavior so `./gradlew :app:assembleRelease` still works in CI, in
 * fresh checkouts, and for sideload-only contributors. The
 * :baselineprofile producer's `release`-derived variant also keeps
 * assembling either way (it needs `buildTypes.release` to have SOME
 * signingConfig — AGP refuses to assemble the release variant
 * otherwise).
 */
val localPropertiesFile = rootProject.file("local.properties")
val localProperties = Properties().apply {
    if (localPropertiesFile.exists()) {
        localPropertiesFile.inputStream().use { load(it) }
    }
}
val releaseStoreFilePath: String? = localProperties.getProperty("storyvox.releaseStoreFile")
val releaseStorePassword: String? = localProperties.getProperty("storyvox.releaseStorePassword")
val releaseKeyAlias: String? = localProperties.getProperty("storyvox.releaseKeyAlias")
val releaseKeyPassword: String? = localProperties.getProperty("storyvox.releaseKeyPassword")
val hasReleaseKeystore: Boolean = releaseStoreFilePath != null &&
    releaseStorePassword != null &&
    releaseKeyAlias != null &&
    releaseKeyPassword != null &&
    file(releaseStoreFilePath!!).exists()

/**
 * Signing-path split for #952 — the sideload APK (attached to GitHub
 * Releases) must be debug-signed to preserve sideload upgrade continuity
 * from every install since v0.4.15, while the Play Store AAB
 * (`publishReleaseBundle` / `bundleRelease`) must be release-signed
 * because Play rejects the checked-in debug keystore.
 *
 * Pre-#952 (v0.7.0 through v0.7.4): `buildTypes.release` always picked
 * the release keystore when [hasReleaseKeystore] was true. Since
 * katana's self-hosted CI runner has the four `storyvox.release*`
 * properties wired up (for the Play path in
 * docs/play-store/RUNBOOK.md), the **APK** attached to every GitHub
 * Release since v0.7.0 was signed with the wrong cert
 * (CN=TechEmpower.org instead of the checked-in androiddebugkey). This
 * silently broke `adb install` over any locally-built debug install
 * with `INSTALL_FAILED_UPDATE_INCOMPATIBLE: signatures do not match`.
 *
 * Resolution: inspect [Gradle.getStartParameter] at configuration time
 * and pick the keystore based on whether the requested task graph
 * contains an AAB / publish target. This is configuration-cache safe —
 * `startParameter.taskNames` is fixed for the build invocation and
 * exposed as a stable Gradle property, not a system-call.
 *
 * Heuristic: any task name containing `bundle` (case-insensitive) or
 * starting with `publish` is treated as a Play-path request and gets
 * the release keystore. Everything else (assembleRelease, installRelease,
 * the macrobenchmark target, fresh-checkout debug builds) gets the
 * checked-in keystore so the resulting APK upgrades any prior
 * sideloaded install in place.
 *
 * Why a heuristic and not product flavors: flavors double the variant
 * matrix and force every consumer of :app — :baselineprofile, the test
 * source sets, the gradle-play-publisher config — to disambiguate. The
 * task-graph check ships the same fix in one place. The cost is that a
 * mixed invocation like `./gradlew :app:assembleRelease :app:bundleRelease`
 * signs BOTH artifacts with the release keystore, but no automation
 * (CI, release runbook) issues that pair — CI only runs
 * `:app:assembleRelease` (see .github/workflows/android.yml), and the
 * Play path runs `:app:publishReleaseBundle` separately.
 *
 * When [hasReleaseKeystore] is false (fresh checkout, contributor without
 * the Play keystore configured), the bundle path falls back to the debug
 * keystore — gradle-play-publisher's `requires credentials` no-op
 * triggers before any upload attempt, so a debug-signed AAB on disk is
 * harmless. The only invariant that matters is "release keystore is
 * never used for an APK that lands in a GitHub Release."
 */
val isBundleOrPublishBuild: Boolean = gradle.startParameter.taskNames.any { taskName ->
    val lower = taskName.lowercase()
    "bundle" in lower || lower.startsWith("publish") || lower.contains(":publish")
}

/**
 * Play Console service-account credentials path — opt-in via local.properties.
 *
 *   storyvox.playPublisher.credentialsFile=/home/jp/.storyvox-keystore/play-service-account.json
 *
 * When set AND the file exists, the gradle-play-publisher tasks
 * (`publishReleaseBundle`, `publishReleaseApk`, `promoteReleaseArtifact`)
 * upload to Play Console Internal Test using that service account. When
 * unset or absent, the plugin's tasks are no-ops — gradle prints
 * "PlayPublisher requires credentials" if someone runs `publish*`
 * without the credential, but every other build/install path is
 * unaffected. See docs/play-store/RUNBOOK.md for the one-time setup.
 */
val playPublisherCredentialsPath: String? = localProperties.getProperty(
    "storyvox.playPublisher.credentialsFile",
)
val hasPlayPublisherCredentials: Boolean = playPublisherCredentialsPath != null &&
    file(playPublisherCredentialsPath!!).exists()

android {
    namespace = "in.jphe.storyvox"
    compileSdk = 36

    defaultConfig {
        applicationId = "org.techempower.candela"
        minSdk = 26
        targetSdk = 35
        versionCode = 227
        versionName = "1.0.3"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true

        // Realm-sigil fields — see app/sigil/Sigil.kt for the name generator.
        // Realm "fantasy" matches Library Nocturne aesthetic and RR's primary genre.
        buildConfigField("String", "SIGIL_REALM", "\"fantasy\"")
        buildConfigField("String", "SIGIL_HASH", "\"$gitHash\"")
        buildConfigField("String", "SIGIL_BRANCH", "\"$gitBranch\"")
        buildConfigField("boolean", "SIGIL_DIRTY", "$gitDirty")
        buildConfigField("String", "SIGIL_BUILT", "\"$buildTime\"")
        buildConfigField(
            "String",
            "SIGIL_REPO",
            "\"https://github.com/techempower-org/storyvox\"",
        )
    }

    signingConfigs {
        // Repo-checked-in keystore so every environment (CI runners, each
        // contributor's machine) signs the APK with the SAME certificate.
        // Without this each cold environment generates a fresh keystore →
        // "App not installed: package conflicts" when a CI APK lands over
        // a locally-built one (or v0.4.13 over v0.4.12 if the runner cache
        // rotated).
        //
        // SECURITY TRADE-OFF (acknowledged): committing the private key
        // means anyone can sign an APK with the same applicationId and
        // Android will accept it as an upgrade. For storyvox today this
        // is an acceptable trade-off — distribution is sideload-only via
        // GitHub Releases, the audience is the developer, and the APKs
        // aren't going through any signed-update channel that this would
        // compromise. Before storyvox is distributed to users at scale
        // (Play Store, F-Droid, anything that relies on signature
        // continuity for security guarantees) the release flavor will
        // need its own keystore stored in CI secrets — see issue tracker.
        getByName("debug") {
            storeFile = file("storyvox-debug.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }

        // Play Store release keystore — only registered when the four
        // `storyvox.release*` properties are present in local.properties
        // AND the file on disk exists. See the long comment near
        // `hasReleaseKeystore` at the top of this file, and the
        // walkthrough in docs/release-keystore.md, for the migration
        // procedure. When the keystore isn't wired up, this block is
        // skipped and `buildTypes.release` falls back to the checked-in
        // debug keystore — preserving today's sideload behavior so a
        // fresh checkout (or the self-hosted CI runner before the
        // properties are pushed there) still produces a working APK.
        if (hasReleaseKeystore) {
            create("release") {
                storeFile = file(releaseStoreFilePath!!)
                storePassword = releaseStorePassword
                keyAlias = releaseKeyAlias
                keyPassword = releaseKeyPassword
            }
        }
    }

    buildTypes {
        release {
            // Issue #529 follow-up — `release` is the SHIPPED build type.
            //
            // Prior history (kept for context): v0.4.15 through v0.5.57
            // shipped from `:app:assembleDebug` because the historical
            // setup put R8 + Baseline Profile + isDebuggable=false on
            // the `debug` block. Functionally a release build wearing
            // a `debug` label. The user-visible side effects — APK
            // filename `app-debug.apk`, `BuildConfig.DEBUG=true`,
            // settings overlay strip leaking onto the reader — were
            // never acceptable; JP filed #529 as a release-quality
            // bug after the 0.5.52/0.5.57 sideload installs showed
            // the "sent #N · queue X/12" debug strip on R5CRB0W66MK.
            //
            // This block carries forward EVERY production-relevant
            // setting from the old debug block:
            //   - isMinifyEnabled = true     (R8 + tree-shaking, #409 pt3)
            //   - isShrinkResources = false  (matches the legacy debug
            //                                 setting; androidTest / IT
            //                                 runs reference resources
            //                                 by name and the shrinker
            //                                 would strip them — same
            //                                 reasoning JP locked in
            //                                 for the debug block)
            //   - proguardFiles              (proguard-android-optimize
            //                                 + the project's own
            //                                 `app/proguard-rules.pro`
            //                                 which carries keep rules
            //                                 for KSP-generated source
            //                                 plugin factories,
            //                                 kotlinx-serialization
            //                                 synthesised serializers,
            //                                 Hilt entry points, Room
            //                                 entities/DAOs, Jsoup,
            //                                 OkHttp)
            //   - signingConfig              (split per #952 — see
            //                                 `isBundleOrPublishBuild`
            //                                 above. APK assemble path
            //                                 keeps the checked-in
            //                                 keystore that every
            //                                 sideload install since
            //                                 v0.4.15 trusts; AAB path
            //                                 swaps to the release
            //                                 keystore that Play
            //                                 requires.)
            //
            // What changes vs the old debug block:
            //   - BuildConfig.DEBUG flips to false naturally because
            //     AGP wires DEBUG=isDebuggable, and the release
            //     buildType's isDebuggable defaults to false
            //     (matching what the old debug block forced
            //     explicitly).
            //   - `isShrinkResources = false` matches the legacy
            //     debug block deliberately. Flipping it on alongside
            //     this rename is a separate decision — leave for a
            //     follow-up so this PR is a clean variant flip and
            //     a R8-rules audit, not a resource-stripping audit.
            isMinifyEnabled = true
            isShrinkResources = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            // #952 — pick the keystore by task-graph intent:
            //   * `:app:bundleRelease` / `:app:publishReleaseBundle`
            //     (the Play AAB path) → release keystore when wired
            //     up. Play rejects the checked-in debug keystore so
            //     this is the only path that produces an uploadable
            //     AAB.
            //   * `:app:assembleRelease` (the GitHub Release APK
            //     path, what CI runs in .github/workflows/android.yml)
            //     → checked-in debug keystore. Continuity-critical:
            //     every sideloaded storyvox install since v0.4.15
            //     trusts that cert; flipping the APK to the release
            //     keystore on v0.7.x silently broke `adb install`
            //     for anyone with a local install. See
            //     `isBundleOrPublishBuild` above for the heuristic.
            //
            // When [hasReleaseKeystore] is false (fresh checkout,
            // contributor without Play credentials), even the bundle
            // path falls back to debug. gradle-play-publisher's
            // `requires credentials` no-op stops any actual upload,
            // so a debug-signed AAB never escapes the build dir.
            signingConfig = if (hasReleaseKeystore && isBundleOrPublishBuild) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
        debug {
            // Developer-only variant for local `./gradlew installDebug`
            // workflows that want a fast iteration loop (no R8) and the
            // ability to attach Android Studio's debugger. NOT shipped —
            // the GitHub release artifact comes from `:app:assembleRelease`
            // per the workflow in `.github/workflows/android.yml`.
            //
            // isDebuggable defaults to true on the debug block; we let
            // AGP keep it that way. BuildConfig.DEBUG = true here,
            // which keeps the on-reader debug overlay's defense-in-depth
            // gate (HybridReaderScreen.kt) active for local iteration.
            //
            // Signing config still points at the checked-in debug
            // keystore so an `installDebug` over a sideloaded release
            // doesn't trip the "package conflicts" upgrade error —
            // same cert chain, same applicationId.
            isMinifyEnabled = false
            isShrinkResources = false
            signingConfig = signingConfigs.getByName("debug")
        }
        // Issue #409 — Macrobenchmark target build type. Non-debuggable
        // (so ART honors the installed Baseline Profile), no R8 (JP's
        // design call queued separately), debug-signed (single
        // keystore). Mirrors release; the BaselineProfile plugin uses
        // this as the producer side's target variant. The output APK
        // is NOT what we ship — the shipped artifact comes from
        // `:app:assembleRelease` now (post-#529). This variant exists so:
        //   1. The BaselineProfileGenerator can install a
        //      non-debuggable target and measure AOT-compiled cold
        //      launch (ART skips profile compilation for debuggable
        //      builds, which would invalidate the with-profile number).
        //   2. The StartupBenchmark gets honest "with profile" /
        //      "without profile" comparisons.
        // The generated `baseline-prof.txt` is merged into
        // :app/src/main/ (mergeIntoMain = true below) so every variant
        // — release, debug, benchmark — bundles it; ProfileInstaller
        // AOT-compiles it on first launch of the non-debuggable
        // release APK.
        create("benchmark") {
            initWith(getByName("release"))
            // signingConfig already inherited from release.initWith.
            // `debuggable = false` already set by initWith too. Adding
            // matchingFallbacks so libraries with only debug/release
            // variants resolve cleanly when consumed from benchmark.
            matchingFallbacks += listOf("release")
            // Profile-enabled but explicitly NOT minified — the JP
            // R8 design call is a separate batch.
            isMinifyEnabled = false
            isShrinkResources = false
            isProfileable = true
            // Skip the BaselineProfile auto-wiring for this build type
            // itself — we don't want a self-referential dependency.
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }


    buildFeatures {
        compose = true
        buildConfig = true
    }

    lint {
        // Issue #409 part 4 — once the debug build went non-debuggable
        // (to activate the bundled Baseline Profile's AOT step at
        // install time), AGP started running `lintVitalAnalyzeDebug`
        // as part of `:app:assembleDebug`. The vital lint check
        // crashes on `:core-ui`'s `A11yLocals.kt` with an
        // "Unexpected failure during lint analysis" — an internal
        // lint bug, not a real code issue (the file compiles +
        // unit-tests pass). We disable the vital pass on release-
        // style builds so the assemble path stays unblocked. Regular
        // `:app:lintDebug` still runs; the vital escalation is the
        // only piece skipped.
        checkReleaseBuilds = false
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src/main/kotlin")
        }
        getByName("test") {
            java.srcDirs("src/test/kotlin")
        }
        // Issue #529 follow-up — release-variant test source set. Holds
        // `ReleaseBuildConfigTest` which pins `BuildConfig.DEBUG == false`
        // for the shipped variant. AGP infers the source set name from
        // the `release` build type; we only need to point java/kotlin at
        // the conventional `kotlin/` subdir (default is `java/`).
        getByName("testRelease") {
            java.srcDirs("src/testRelease/kotlin")
        }
    }

    testOptions {
        unitTests {
            // Robolectric needs Android resources visible to the test classpath
            // so it can spin up a stub application context. Required for
            // StoryvoxRoutesTest, which calls into android.net.Uri.
            isIncludeAndroidResources = true
        }
    }

    packaging {
        resources {
            excludes += setOf(
                "/META-INF/{AL2.0,LGPL2.1}",
                "/META-INF/DEPENDENCIES",
                "/META-INF/LICENSE*",
                "/META-INF/NOTICE*",
                "/META-INF/*.kotlin_module",
            )
        }
    }

    // Issue #529 follow-up — rename the local-build APK so the file on
    // disk matches the GitHub release asset naming (storyvox-vX.Y.Z.apk).
    // Without this `./gradlew :app:assembleRelease` writes
    // `app/build/outputs/apk/release/app-release.apk` — fine for AGP
    // internals but JP's sideload muscle memory (and any installer
    // tooling like `adb install storyvox-*.apk`) expects the branded
    // name. The CI workflow's `cp app-release.apk storyvox-${TAG}.apk`
    // step still works regardless because we don't rename when there's
    // no versionName attached — but for tagged local builds this hands
    // back the same filename CI publishes.
    //
    // We rename for `release` and `benchmark` only; `debug` stays
    // `app-debug.apk` so a developer running `./gradlew installDebug`
    // sees AGP's default naming and can't confuse the dev APK with the
    // shipped one.
}

androidComponents {
    onVariants { variant ->
        if (variant.name == "release" || variant.name == "benchmark") {
            val suffix = if (variant.name == "benchmark") "-benchmark" else ""
            variant.outputs.forEach { output ->
                output.outputFileName.set(
                    "storyvox-v${android.defaultConfig.versionName}$suffix.apk"
                )
            }
        }
    }
}

/**
 * gradle-play-publisher configuration.
 *
 * When `storyvox.playPublisher.credentialsFile` is set in local.properties
 * and the file exists, `./gradlew publishReleaseBundle` uploads the signed
 * AAB to Play Console's Internal Test track with no browser interaction.
 * The service-account JSON must come from a Google Cloud project that's
 * linked to the Play Console developer account with at least the "Release
 * manager" role — see docs/play-store/RUNBOOK.md for the one-time setup.
 *
 * Defaults below are deliberately conservative:
 *  - `track = "internal"` — uploads land in Internal Test, never auto-go
 *    to Production. Promote via `promoteArtifact` or the Play Console UI.
 *  - `releaseStatus = "draft"` — the upload is staged, not auto-released
 *    even within Internal Test. JP reviews + clicks "Release" in Play
 *    Console for the first cycle; later releases can flip to "completed".
 *  - `defaultToAppBundles = true` — `publishBundle` (AAB) is the canonical
 *    path. APK uploads only run if explicitly asked for.
 *  - `commit = false` — every gradle invocation builds up an "edit"
 *    on Play Console without publishing it; the explicit `publishApps`
 *    task commits the bundle so a failed CI run never half-publishes.
 *
 * No-op when credentials are absent: the plugin's tasks emit
 * "PlayPublisher requires credentials" but the rest of the build is
 * unaffected. Configuration-cache safe because we read the path eagerly
 * above and use it as a plain String at configuration time.
 */
play {
    if (hasPlayPublisherCredentials) {
        serviceAccountCredentials.set(file(playPublisherCredentialsPath!!))
    }
    track.set("internal")
    releaseStatus.set(com.github.triplet.gradle.androidpublisher.ReleaseStatus.DRAFT)
    defaultToAppBundles.set(true)
    commit.set(false)
    // Resolution strategy: ignore version conflicts with the current Play
    // Console listing. AGP versionCode is the source of truth — if a
    // half-uploaded edit from a prior run is hanging around, we override
    // it rather than failing the new release.
    resolutionStrategy.set(com.github.triplet.gradle.androidpublisher.ResolutionStrategy.IGNORE)
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        freeCompilerArgs.addAll("-Xannotation-default-target=param-property")
    }
}

dependencies {
    implementation(project(":core-data"))
    implementation(project(":core-llm"))
    implementation(project(":core-playback"))
    implementation(project(":core-ui"))
    implementation(project(":source-royalroad"))
    implementation(project(":source-github"))
    implementation(project(":source-mempalace"))
    implementation(project(":source-rss"))
    implementation(project(":source-epub"))
    implementation(project(":source-epub-writer"))
    implementation(project(":source-outline"))
    implementation(project(":source-gutenberg"))
    implementation(project(":source-ao3"))
    implementation(project(":source-standard-ebooks"))
    implementation(project(":source-wikipedia"))
    implementation(project(":source-wikisource"))
    // Issue #417 — :source-radio replaces :source-kvmr. Same Gradle
    // module, generalized: curated stations (KVMR, KQED, KCSB,
    // KXPR, SomaFM Groove Salad) + Radio Browser API search.
    implementation(project(":source-radio"))
    // Issue #417 — JSON serialization for RadioConfigImpl's starred-
    // stations DataStore payload.
    implementation(libs.kotlinx.serialization.json)
    implementation(project(":source-notion"))
    implementation(project(":source-hackernews"))
    implementation(project(":source-arxiv"))
    implementation(project(":source-plos"))
    implementation(project(":source-discord"))
    implementation(project(":source-telegram"))
    // Issue #454 — Slack Web API backend. Channels-as-fictions via
    // Bot Token auth (xoxb-…). Mirrors :source-telegram's leaf
    // shape; the SlackConfigImpl + DataStore wiring lives in :app.
    implementation(project(":source-slack"))
    // Issue #457 — Matrix Client-Server API backend. Federated
    // open-standard chat (rooms-as-fictions, messages-as-chapters);
    // architectural twin to :source-discord. Default OFF on fresh
    // installs — the chip is hidden until the user opts in via
    // Settings → Plugins and pastes both a homeserver URL and an
    // access token.
    implementation(project(":source-matrix"))
    // Issue #472 — magic-link Readability catch-all. Must be on the
    // app classpath so its KSP-generated SourcePluginDescriptor binding
    // joins the Hilt multibinding set the registry consumes.
    implementation(project(":source-readability"))
    // Issue #502 — Palace Project OPDS library backend. First library-
    // borrowing source in the storyvox roster; ships non-DRM titles
    // only in v1 (LCP DRM titles surface greyed-out with an "open in
    // Palace app" deep-link CTA). Libby + Hoopla follow-up scopes are
    // documented under scratch/libby-hoopla-palace-scope/ but deferred
    // to their own PRs.
    implementation(project(":source-palace"))
    implementation(project(":source-azure"))
    implementation(project(":core-sync"))
    implementation(project(":feature"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.startup)
    implementation(libs.bundles.lifecycle)
    implementation(libs.bundles.coroutines)

    // Compose
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.bundles.compose)
    debugImplementation(libs.androidx.compose.ui.tooling)

    // Navigation
    implementation(libs.androidx.navigation.compose)

    // Chrome Custom Tabs for the Anthropic Teams OAuth handoff (#181)
    implementation(libs.androidx.browser)

    // Hilt
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.androidx.hilt.navigation.compose)
    implementation(libs.androidx.hilt.work)
    ksp(libs.androidx.hilt.compiler)

    // WorkManager
    implementation(libs.androidx.work.runtime.ktx)

    // DataStore (settings persistence)
    implementation(libs.androidx.datastore.preferences)

    // SAF helper for the EPUB import folder picker (#235)
    implementation(libs.androidx.documentfile)

    coreLibraryDesugaring(libs.android.desugar.jdk.libs)

    // OkHttp for the suggested-feeds registry fetch (#246).
    implementation(libs.okhttp)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    // OkHttp on the test classpath only — SettingsRepositoryBufferTest
    // constructs a real PalaceDaemonApi (with no HTTP traffic) so the
    // repo signature is satisfied. Production transitively pulls okhttp
    // via :source-mempalace; tests need an explicit testImplementation
    // because the source module is `implementation` (not `api`) which
    // doesn't expose its dep classpath to consumers' tests.
    testImplementation(libs.okhttp)
    // Robolectric supplies a real android.net.Uri implementation under JVM
    // unit tests so StoryvoxRoutesTest can verify the v0.4.25 encoding fix
    // (Uri.encode in the route-builder) — the framework stub jar throws
    // "Method not mocked" on every Uri.* call and isReturnDefaultValues
    // would just hand us null, which won't catch a regression. This is
    // the only Robolectric-using test in the repo today; if more land
    // they should reuse this dep, not add their own.
    testImplementation(libs.robolectric)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)

    // Issue #409 — ProfileInstaller compiles the bundled
    // `baseline-prof.txt` at first-run on devices that don't go through
    // a Play Store install (sideload APKs from GitHub Releases). Without
    // this dep the profile is dead code: it ships inside the APK but
    // never reaches the ART compiler. ProfileInstaller wakes up on
    // first app launch, queues the AOT compile on a background thread,
    // and the next cold-launch benefits.
    implementation(libs.androidx.profileinstaller)

    // Tells the AndroidX Baseline Profile Gradle plugin which producer
    // module owns the generator task. Pair-matches the
    // `targetProjectPath = ":app"` declaration in :baselineprofile.
    "baselineProfile"(project(":baselineprofile"))
}

/**
 * Issue #409 — Baseline Profile consumer-side config.
 *
 * `mergeIntoMain = true` makes the plugin write the generated profile
 * to `app/src/main/generated/baselineProfiles/baseline-prof.txt`
 * rather than the default per-variant path
 * (`app/src/release/generated/baselineProfiles/`). This keeps the
 * profile available to every variant — release (shipped), debug
 * (local iteration), benchmark — without per-variant src dirs.
 *
 * `saveInSrc = true` means the profile is checked into git (default
 * behavior in 1.4.x). Without this the profile would land in the
 * build directory only, forcing a regenerate on every clean CI run.
 * We want it committed so the release APK has it from the start.
 *
 * `automaticGenerationDuringBuild = false` keeps the BaselineProfile
 * generation OFF the critical-path build. CI's `:app:assembleRelease`
 * path needs to stay fast (~2 min); profile regeneration is an
 * instrumented test (~6 min on Tab A7 Lite) so we run it manually on
 * tag pushes or when the nav graph changes.
 *
 * NOTE (#529 follow-up, v0.5.58): ProfileInstaller AOT-compiles the
 * bundled profile on non-debuggable APKs. Since the shipped variant
 * is now `release` (isDebuggable=false naturally), the bundled
 * Baseline Profile is finally active on the artifact JP sideloads.
 * The cold-launch win this infrastructure was wired for (sub-1.5 s
 * on R83W80CAFZB) lands with this variant flip.
 */
baselineProfile {
    mergeIntoMain = true
    saveInSrc = true
    automaticGenerationDuringBuild = false
}
