package `in`.jphe.storyvox.data.db.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Issue #383 — cross-source Inbox event. One row per source-emitted
 * notification (new chapters detected by the poller, live programs
 * starting, articles updated, etc.). Powers the Library "Inbox" sub-tab
 * — a chronological, source-agnostic feed of "something happened in
 * your library."
 *
 * Design notes:
 *  - Autogenerated [id] (not a composite PK) because two events for the
 *    same fiction at different times should both be visible in the feed
 *    until the user clears them. Re-coalescing duplicates is the
 *    repository's job at insert time (e.g. "3 new chapters in X" not
 *    "1 new chapter" × 3) — see [`in`.jphe.storyvox.data.repository.InboxRepository].
 *  - [sourceId] mirrors `Fiction.sourceId` and lets the UI render a
 *    backend-specific icon without joining back through fiction (the
 *    fiction row may have been removed and we still want to render the
 *    event). Stored as the backend's stable id string ("royalroad",
 *    "kvmr", "wikipedia", etc.), same convention as
 *    `SOURCE_*_ENABLED` settings keys.
 *  - [fictionId] / [chapterId] are nullable so events that don't deep-
 *    link to a chapter (e.g. "Wikipedia article updated") still fit.
 *    The [deepLinkUri] string is the authoritative tap-target — a
 *    `storyvox://reader/{fictionId}/{chapterId}` URL or a custom
 *    backend-specific scheme.
 *  - No FK to fiction/chapter: deletes of those tables shouldn't
 *    cascade-wipe Inbox history. If a fiction is removed the event row
 *    still renders with a fallback monogram (mirrors the HistoryEntry
 *    null-title handling). The repository can opportunistically prune
 *    on `markRead` / clear-all if storage becomes an issue.
 *  - Index on [ts] for the `ORDER BY ts DESC` feed query; index on
 *    [isRead] for the unread-count flow (`SELECT COUNT(*) WHERE
 *    isRead = 0` is the hot read).
 */
@Entity(
    tableName = "inbox_event",
    indices = [
        Index(value = ["ts"]),
        Index(value = ["isRead"]),
        Index(value = ["sourceId", "fictionId"]),
    ],
)
data class InboxEvent(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    /** Backend that produced the event — "royalroad", "kvmr", "wikipedia", … */
    val sourceId: String,
    /** Fiction the event relates to, or null for source-wide events. */
    val fictionId: String?,
    /** Specific chapter the event deep-links to, or null. */
    val chapterId: String?,
    /** One-line label — "3 new chapters in The Wandering Inn". */
    val title: String,
    /** Optional secondary line — chapter title, program name, etc. */
    val body: String?,
    /** Event epoch millis. */
    val ts: Long,
    /** True once the user has tapped the row (or markAllRead fired). */
    val isRead: Boolean = false,
    /**
     * Tap-target. Storyvox-internal deep-link URI string —
     * `storyvox://reader/<fictionId>/<chapterId>` for chapter events,
     * `storyvox://fiction/<fictionId>` for source-wide events. The UI
     * decodes it via [NavController]; null means "open the source's
     * default surface" (rare — we always try to give the user
     * something to tap).
     */
    val deepLinkUri: String?,
)
